create database DBMS_Project;
use DBMS_Project;

CREATE TABLE CRIMINAL(
C_ID VARCHAR(10) PRIMARY KEY,
C_NAME VARCHAR(50) NOT NULL,
C_AGE NUMERIC(3) NOT NULL,
CRIME_COMMITTED VARCHAR(100) NOT NULL,
ARREST_DATE DATE NOT NULL,
BAIL_DATE DATE NOT NULL);


CREATE TABLE LAWYER(
L_ID VARCHAR(10) PRIMARY KEY,
L_NAME VARCHAR(100),
CASE_WON INT,
CASE_LOST INT);

CREATE TABLE PROSECUTOR(
P_ID VARCHAR(10) PRIMARY KEY,
L_ID VARCHAR(10),
FOREIGN KEY (L_ID) REFERENCES LAWYER(L_ID));

CREATE TABLE DEFENDANT(
D_ID VARCHAR(10) PRIMARY KEY,
L_ID VARCHAR(10),
FOREIGN KEY (L_ID) REFERENCES LAWYER(L_ID));

CREATE TABLE JUDGE(
J_ID VARCHAR(10) PRIMARY KEY,
J_NAME VARCHAR(50) );

CREATE TABLE BRANCH(
B_ID VARCHAR(10) PRIMARY KEY,
B_NAME VARCHAR(50));

CREATE TABLE OFFICER(
O_ID VARCHAR(10) PRIMARY KEY,
B_ID VARCHAR(10),
O_NAME VARCHAR(50) ,
DEPARTMENT VARCHAR (50),
FOREIGN KEY (B_ID) REFERENCES BRANCH(B_ID));

CREATE TABLE CRIMINAL_TRIAL(
C_ID VARCHAR(10),
J_ID VARCHAR(10),
L_ID VARCHAR(10),
TRIAL_DATE DATE NOT NULL,
FOREIGN KEY(C_ID) REFERENCES CRIMINAL(C_ID),
FOREIGN KEY(J_ID) REFERENCES JUDGE(J_ID),
FOREIGN KEY(L_ID) REFERENCES LAWYER(L_ID));

CREATE TABLE CASE_COURT(
CASE_ID VARCHAR(10) PRIMARY KEY,
C_ID VARCHAR(10) ,
J_ID VARCHAR(10),
O_ID VARCHAR(10),
L_ID VARCHAR(10),
VERDICT VARCHAR(100),
FOREIGN KEY(C_ID) REFERENCES CRIMINAL(C_ID),
FOREIGN KEY(J_ID) REFERENCES JUDGE(J_ID),
FOREIGN KEY(L_ID) REFERENCES LAWYER(L_ID),
FOREIGN KEY(O_ID) REFERENCES OFFICER(O_ID));

CREATE TABLE WITNESS(
W_ID VARCHAR(10) PRIMARY KEY,
CASE_ID VARCHAR(10),
WITNESS_NAME VARCHAR(50),
WITNESS_AGE NUMERIC(3),
FOREIGN KEY(CASE_ID) REFERENCES CASE_COURT(CASE_ID));
